version: "2"
run:
  build-tags:
    - development
    - awstest
linters:
  default: all
  disable:
    - depguard
    - err113 # TODO
    - exhaustruct
    - noinlineerr
    - nonamedreturns
    - wrapcheck # TODO
    - wsl # obsoleted by wsl_v5
  settings:
    cyclop:
      max-complexity: 45 # TODO: reduce
      package-average: 10.2 # TODO: reduce
    decorder:
      disable-dec-num-check: true
      disable-dec-order-check: false
    errcheck:
      #severity: warn
      disable-default-exclusions: false
      check-type-assertions: true
      check-blank: true
    errchkjson:
      #severity: Warn
      report-no-exported: true
    errorlint:
      asserts: true
    exhaustive:
      check:
        - switch
        - map
      default-signifies-exhaustive: true
    funlen:
      lines: 800 # TODO: reduce
      statements: 384 # TODO: reduce
      ignore-comments: true
    gocognit:
      min-complexity: 603 # TODO: reduce
    goconst:
      min-occurrences: 6
    gocritic:
      disabled-checks:
        - commentFormatting
        - exposedSyncMutex
        - commentedOutCode
      enabled-tags:
        - diagnostic
        - style
        - performance
        - experimental
        - opinionated
      settings:
        captLocal:
          paramsOnly: false
        elseif:
          skipBalanced: true
        hugeParam:
          sizeThreshold: 2265 # TODO: decrease
        nestingReduce:
          bodyWidth: 5
        rangeExprCopy:
          sizeThreshold: 512
          skipTestFuncs: true
        rangeValCopy:
          sizeThreshold: 201
          skipTestFuncs: true
        truncateCmp:
          skipArchDependent: true
        underef:
          skipRecvDeref: true
    gocyclo:
      min-complexity: 235 # TODO: reduce
    godot:
      scope: all
      exclude:
        - ^ HAS_.*
        - ^ \[.*\]$
      capital: true
    gosec:
      config:
        G302: "0640"
        G306: "0640"
    govet:
      enable-all: true
      settings:
        shadow:
          strict: true
    ireturn:
      allow:
        - empty
        - error
        - stdlib
        - generic
    lll:
      line-length: 196 # TODO: reduce
      tab-width: 1
    maintidx:
      under: 10
    makezero:
      always: false
    mnd:
      ignored-numbers: ["2"]
    nakedret:
      max-func-lines: 120 # TODO: reduce
    nestif:
      min-complexity: 5
    nlreturn:
      block-size: 2
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    predeclared:
      qualified-name: false
    revive:
      rules: []
    testpackage:
      skip-regexp: (export|internal)_test\.go
    thelper:
      test:
        first: true
        name: true
        begin: true
      benchmark:
        first: true
        name: true
        begin: true
      tb:
        first: true
        name: true
        begin: true
    unparam:
      check-exported: false
    unused:
      field-writes-are-uses: true
      post-statements-are-reads: false
      exported-fields-are-used: false
      parameters-are-used: true
      local-variables-are-used: false
      generated-is-used: false
    varnamelen:
      max-distance: 25
      min-name-length: 2
      check-receiver: false
      check-return: true
      check-type-param: true
      ignore-names:
        - err
        - db
        - t0
        - t1
        - t2
        - tc
        - T
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-chan-recv-ok: true
      ignore-decls:
        - i int
        - j int
        - T any
    wsl:
      strict-append: true
      allow-assign-and-call: true
      allow-multiline-assign: true
      force-case-trailing-whitespace: 0
      allow-trailing-comment: false
      allow-separated-leading-comment: false
      allow-cuddle-declarations: false
      force-err-cuddling: false
  exclusions:
    warn-unused: true
    generated: strict
    rules:
      - linters:
          - errcheck
          - gochecknoglobals
          - godot
          - gosec
          - govet
          - lll
        path: _test\.go
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      simplify: true
    gofumpt:
      extra-rules: true
output:
  show-stats: true
